image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        pipenv install;
        pipenv run start;
    - command: python3 welcome.py

vscode:
  extensions:
    - kevinrose.vsc-python-indent@1.12.0:NOHaOm1IToFrG4fit4+hUw==